#プログラムの中に直接こういった設定を明記するのではなく、プログラムの外部に設定を記述する
#コードと設定を分けることで変更に強いコードになる
#いわばここは「このSpring Bootアプリをどう動かすか」を指定する設定ファイルとして機能している
#主な用途　ポート、DB接続、ログ、画面、アップロード、独自設定


spring.application.name=armory
#文字通りこのアプリの名前を明記している
server.port=8080
#Webサーバーを何番ポートで待ち受けるか（このアプリのポート番号は8080番ですよ）
#これによりSpring Bootを起動するとhttp://localhost:8080	でアクセスできる

#DB
spring.datasource.url=jdbc:postgresql://localhost:5432/armory
#jdbc→JavaからDBにアクセスするための仕組み　postgresql→接続先のDB
#localhost:5432→DBの場所及びポート番号（localhost→自分のパソコン　5432→ポスグレの標準ポート番号）
#末尾のarmoryはデータベース名（ここに接続する）
spring.datasource.username=postgres
#ポスグレにログインするときのユーザー名（今回はpostgres）
spring.datasource.password=postgrestest
#DBに接続するためのパスワードを設定している
#${}でプレースホルダになっている
#パスワードが何も設定されていなければ、仮パスワードとしてchangemeが使用される
#DB_PASSWORD=abc123という環境変数が設定されていれば、それがパスワードとして使用される
#パスワードは環境変数で渡し、ファイルに直書きしない
#環境変数とは、OS（Windows）が持っている、プログラムに情報を渡すための仕組み プロパティには=${DB_PASSWORD}と書き
#この環境変数を使ってくださいと支持する
#spring.datasource.password=${DB_PASSWORD:changeme}　環境変数を使用し、未設定の場合はchangemeを使ってください

#schema.sql / data.sqlを外部でも実行
spring.sql.init.mode=always
#DBの種類に関係なく、SQLの初期化処理を実行する
#開発やテスト環境でのデータリセットや初期データ投入に便利だが、本番環境では注意が必要
spring.sql.init.encoding=UTF-8
#このSQLファイルをUTF-8として読み込み、日本語を正しく扱えるようにする

#MyBatis
mybatis.type-aliases-package=com.example.armory.entity
#MyBatisクラスでエンティティクラスを簡単に扱えるようにする設定
#この設定によりMyBatisが当該パッケージを認識し、MyBatisの機能を使用できる
mybatis.configuration.map-underscore-to-camel-case=true
#なんかこの設定によってSQL「created_at」とJava「createdAt」の表記揺れを自動処理して紐づけてくれる

#upload
spring.servlet.multipart.max-file-size=5MB
#画像のupload
app.upload-dir=./uploads
spring.servlet.multipart.max-request-size=6MB

#log
logging.level.com.example.armory=DEBUG
spring.thymeleaf.cache=false

#＠ValueでJavaコード内で設定値を扱うこともできる property:${キー名} Java内:@Value("${キー名}")